FROM debian:bullseye

COPY . .

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates openssl x11vnc xvfb chromium wget firefox-esr libpci-dev default-jre xterm xorg xserver-xorg-video-dummy procps fluxbox curl tcpdump iproute2 dnsutils strace && \
    apt-get remove -y xserver-xorg-legacy && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install ./google-chrome-stable_current_amd64.deb && \
    mkdir ~/.vnc && \
    touch ~/.vnc/passwd && \
    #mv 10-headless.conf /etc/X11/xorg.conf.d/10-headless.conf && \
    mkdir /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix

EXPOSE 5900

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user} 

ENV DISPLAY :0

RUN x11vnc -storepasswd "password" ~/.vnc/passwd && \
    touch /home/appuser/.Xauthority && \
    chmod 777 /home/appuser/.Xauthority

#RUN mv .xinitrc /home/appuser/.xinitrc

USER ${uid}

ENTRYPOINT ["sh", "start.sh"]
